### ISSUE TITLE
NameError: uninitialized constant Module::Numerizer when running example

### ISSUE THREAD

**Issue by JesseAldridge** [noctivityinc/tickle#11]
```
irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> require 'tickle'
=> true
irb(main):003:0> Tickle.parse('day')
NameError: uninitialized constant Module::Numerizer
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tickle-0.1.7/lib/tickle/tickle.rb:198:in `normalize'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tickle-0.1.7/lib/tickle/tickle.rb:188:in `block in post_tokenize'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tickle-0.1.7/lib/tickle/tickle.rb:187:in `each'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tickle-0.1.7/lib/tickle/tickle.rb:187:in `post_tokenize'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tickle-0.1.7/lib/tickle/tickle.rb:74:in parse'
        from (irb):3
        from C:/Ruby192/bin/irb:12:in `<main>'
```

I'm a ruby newb though, so I'm probably just doing something wrong.

**Comment by brunohq** [comment]
same problem in here.

**Comment by JesseAldridge** [comment]
Me and my buddy got things working in this fork:  https://github.com/dan335/tickle

But there were still more weird issues with tickle.  And the project seems to be abandoned.  I would suggest using [ice_cube](http://www.ruby-forum.com/topic/208729) instead and handling any natural language parsing yourself.
